services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
      - ./credentials.json:/app/credentials.json:ro
    env_file: .env
    environment:
      - NODE_ENV=production
    networks:
      - evolution-net
    restart: unless-stopped

networks:
  evolution-net:
    name: evolution-net
#    external: true
